# version: 1.0.0
add_newline = false
format = """
$username\
$fill\
$git_branch\
$git_status\
$git_metrics\
$directory\
$fossil_branch\
$package\
$c\
$cpp\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$python\
$rlang\
$ruby\
$rust\
$scala\
$vlang\
$zig\
$bun\
$conda\
$pixi\
$crystal\
$time \
$line_break\
$character \
"""

[character]
format = "$symbol"
success_symbol = "[◎](bold italic bright-yellow)"
error_symbol = "[○](italic purple)"
# success_symbol = "[▸▹ ](bold italic bright-yellow)"
vimcmd_symbol = "[■](italic dimmed green)"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[fill]
symbol = ' '

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%T"
utc_time_offset = "local"
style = "italic dimmed white"

# [git_branch]
# format = " [$branch(:$remote_branch)]($style)"
# symbol = "[△](bold italic bright-blue)"
# style = "italic bright-blue"
# truncation_symbol = "⋯"
# truncation_length = 11
# ignore_branches = ["main", "master"]
# only_attached = true

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_commit]
tag_symbol = '  '

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic yellow)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = true

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'

# lang
[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
# symbol = "⨀ "
symbol = " "
style = "bold bright-yellow"

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
# format = " [node](italic) [◫ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "[⌉](bold bright-blue)⌊ "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "◆ "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
# symbol = "⊃ "
symbol = ""
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed yellow italic bold"

[c]
# symbol = "ℂ "
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cpp]
# symbol = "ℂ "
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = "◯ "
format = " conda [$symbol$environment]($style)"

[dart]
# symbol = "◁◅ "
symbol = " "
format = " dart [$symbol($version )]($style)"

[elixir]
# symbol = "△ "
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
# symbol = "◩ "
symbol = " "
format = " elm [$symbol($version )]($style)"

[golang]
# symbol = "∩ "
symbol = " "
format = " go [$symbol($version )]($style)"

[java]
# symbol = "∪ "
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[julia]
# symbol = "◎ "
symbol = " "
format = " jl [$symbol($version )]($style)"

[nim]
symbol = "▴▲▴ "
format = " nim [$symbol($version )]($style)"

[zig]
symbol = " "
format = " [$symbol($version )]($style)"
