add_newline = false
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "
format = "[$symbol($version )]($style)"

[azure]
symbol = "az "
format = "[$symbol($version )]($style)"

[buf]
symbol = "buf "
format = "[$symbol($version )]($style)"

[bun]
symbol = "bun "
format = "[$symbol($version )]($style)"

[c]
symbol = "C "
format = "[$symbol($version )]($style)"

[cpp]
symbol = "C++ "
format = "[$symbol($version )]($style)"

[cobol]
symbol = "cobol "
format = "[$symbol($version )]($style)"

[conda]
symbol = "conda "
format = "[$symbol($version )]($style)"

[container]
symbol = "container "

[crystal]
symbol = "cr "
format = "[$symbol($version )]($style)"

[cmake]
symbol = "cmake "
format = "[$symbol($version )]($style)"

[daml]
symbol = "daml "
format = "[$symbol($version )]($style)"

[dart]
symbol = "dart "
format = "[$symbol($version )]($style)"

[deno]
symbol = "deno "
format = "[$symbol($version )]($style)"

[dotnet]
symbol = ".NET "
format = "[$symbol($version )]($style)"

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "
format = "[$symbol($version )]($style)"

[elm]
symbol = "elm "
format = "[$symbol($version )]($style)"

[fennel]
symbol = "fnl "
format = "[$symbol($version )]($style)"

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "
format = "[$symbol($version )]($style)"

[git_branch]
symbol = "git "

[gleam]
symbol = "gleam "
format = "[$symbol($version )]($style)"

[golang]
symbol = "go "
format = "[$symbol($version )]($style)"

[gradle]
symbol = "gradle "
format = "[$symbol($version )]($style)"

[guix_shell]
symbol = "guix "

[haskell]
symbol = "haskell "
format = "[$symbol($version )]($style)"

[helm]
symbol = "helm "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = "hg "

[java]
symbol = "java "
format = "[$symbol($version )]($style)"

[julia]
symbol = "jl "
format = "[$symbol($version )]($style)"

[kotlin]
symbol = "kt "
format = "[$symbol($version )]($style)"

[lua]
symbol = "lua "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = "nodejs "
format = "[$symbol($version )]($style)"

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "

[nim]
symbol = "nim "
format = "[$symbol($version )]($style)"

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "
format = "[$symbol($version )]($style)"

[opa]
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "
format = "[$symbol($version )]($style)"

[php]
symbol = "php "
format = "[$symbol($version )]($style)"

[pijul_channel]
symbol = "pijul "

[pixi]
symbol = "pixi "
format = "[$symbol($version )]($style)"

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "
format = "[$symbol($version )]($style)"

[python]
symbol = "py "
format = "[$symbol($version )]($style)"

[quarto]
symbol = "quarto "
format = "[$symbol($version )]($style)"

[raku]
symbol = "raku "

[rlang]
symbol = "r "
format = "[$symbol($version )]($style)"

[ruby]
symbol = "rb "
format = "[$symbol($version )]($style)"

[rust]
symbol = "rs "
format = "[$symbol($version )]($style)"

[scala]
symbol = "scala "
format = "[$symbol($version )]($style)"

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
format = "[$symbol($version )]($style)"

[typst]
symbol = "typst "
format = "[$symbol($version )]($style)"

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
format = "[$symbol($version )]($style)"
