[manager]
show_hidden = true

[opener]
edit = [
  { run = 'notepad4 %*',    orphan = true, desc = "Notepad4",           for = "windows" },
  { run = 'notepad4 -w %*', block = true,  desc = "Notepad4 (block)",   for = "windows" },
]
